---
- name: Install gaming packages
  hosts: localhost
  become: true
  vars_files: [../vars.yml]
  tasks:
    - name: Install flatpak
      include_tasks: ../_install_flatpak.yml
    - block:
        - name: Install Bottles
          flatpak:
            name: com.usebottles.bottles
            state: present
        - name: Configure permissions for Bottles
          shell:
            cmd: >
              flatpak override --user \
                --filesystem=xdg-data/applications \
                com.usebottles.bottles
      become_user: '{{ user }}'
