---
- name: Install dev pkgs
  hosts: localhost
  become: true
  vars_files: [../vars.yml]

  tasks:
    # Base DevOps
    - name: Install base DevOps pkgs
      block:
        - name: Create local dirs
          include_tasks: '{{ ansible_path }}/_create_local_dirs.yml'

        - name: Check zsh existence
          include_tasks: '{{ ansible_path }}/_check_zsh.yml'

        - name: Install pkgs to Fedora
          dnf:
            name: awscli
            state: latest
            update_cache: true
            install_weak_deps: false
          when: ansible_distribution=="Fedora"

        - name: Install pkgs to Debian
          apt:
            name: awscli
            state: latest
            update_cache: true
          when: ansible_distribution=="Debian"

        - name: Install terraform-switch
          block:
            - name: Set pkg vars
              set_fact:
                github_username: warrensbox
                github_reponame: terraform-switcher
                artifact_name: terraform-switcher
                arch_type: linux_amd64
                extensoin: tar.gz
                pkg_name: tfswitch
            - name: Install {{ pkg_name }}
              include_tasks: '{{ ansible_path }}/_install_pkg_from_github.yml'

        - name: Make devops omz config symlink
          file:
            src: '{{ omz_path }}/devops_zsh'
            dest: '{{ local_config_path }}/omz/devops_zsh'
            state: link
            force: true
            owner: '{{ user }}'
            mode: 0700
          when: zsh_exist.stat.exists
          become_user: '{{ user }}'

      tags: devops

    # VSCodium
    - name: Install and config VSCodium
      block:
        - name: Install VSCode to Fedora
          block:
            - name: Add VSCodium repo to Fedora
              yum_repository:
                name: vscodium
                description: vscodium repository
                baseurl: https://download.vscodium.com/rpms/
                enabled: true
                gpgkey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
                gpgcheck: true
                metadata_expire: 3600
            - name: Install VSCodium to Fedora
              dnf:
                name: codium
                state: latest
                update_cache: true
                install_weak_deps: false
          when: ansible_distribution=="Fedora"

        - name: Install VSCode to Debian
          block:
            - name: Add VSCodium repo to Debian
              block:
                - name: Add apt GPG key
                  get_url:
                    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
                    dest: /etc/apt/trusted.gpg.d/vscodium-archive-keyring.asc
                - name: Add apt repository
                  apt_repository:
                    repo: deb [ signed-by=/etc/apt/trusted.gpg.d/vscodium-archive-keyring.asc ] https://download.vscodium.com/debs
                      vscodium main
                    state: present
            - name: Install VSCodium to Debian
              apt:
                name: codium
                state: latest
                update_cache: true
          when: ansible_distribution=="Debian"

        - name: Install VSCodium extensoins
          command:
            cmd: codium --install-extension {{ item }}
          with_items:
            - dcasella.monokai-plusplus
            - foxundermoon.shell-format
            - Gruntfuggly.todo-tree
            - lonefy.vscode-JS-CSS-HTML-formatter
            - mads-hartmann.bash-ide-vscode
            - MattiasBaake.vscode-snippets-for-ansible
            - PKief.material-icon-theme
            - redhat.vscode-yaml
            - timonwong.shellcheck
            - vscodevim.vim
            - wholroyd.jinja
          become_user: '{{ user }}'

      tags: vscodium

    # Virtualization
    - name: Install and config virtualization
      block:
        - name: Check zsh existence
          include_tasks: '{{ ansible_path }}/_check_zsh.yml'

        - name: Install virt pkgs to Fedora
          dnf:
            name:
              - gnome-boxes
              - vagrant
              - vagrant-libvirt
              - vagrant-sshfs
            state: latest
            update_cache: true
            install_weak_deps: false
          when: ansible_distribution=="Fedora"

        - name: Install virt pkgs to Debian
          apt:
            name:
              - gnome-boxes
              - libvirt-daemon-system
              - vagrant
              - vagrant-libvirt
              - vagrant-sshfs
            state: latest
            update_cache: true
          when: ansible_distribution=="Debian"

        - name: Config virt dirs
          block:
            - name: Config Gnome Boxes images dirs
              shell:
                cmd: |
                  mkdir -p {{ gnome_boxes_local_path }}
                  {{ script_path }}/_make_btrfs_subvols.sh {{ gnome_boxes_local_images_path }} {{ gnome_boxes_dir_name }}
                  chattr +C {{ gnome_boxes_local_images_path }}
              environment:
                BACKUP_PATH: '{{ backup_path}}'
              vars:
                gnome_boxes_dir_name: gnome-boxes
                gnome_boxes_local_path: '{{ local_share_path }}/{{ gnome_boxes_dir_name }}'
                gnome_boxes_local_images_path: '{{ gnome_boxes_local_path }}/images'
            - name: Config libvirt images dirs
              shell:
                cmd: |
                  mkdir -p {{ libvirt_local_path }}
                  {{ script_path }}/_make_btrfs_subvols.sh {{ libvirt_local_images_path }} {{ libvirt_dir_name }}
                  chattr +C {{ libvirt_local_images_path }}
              environment:
                BACKUP_PATH: '{{ backup_path }}'
              vars:
                libvirt_dir_name: libvirt
                libvirt_local_path: '{{ local_share_path }}/{{ libvirt_dir_name }}'
                libvirt_local_images_path: '{{ libvirt_local_path }}/images'
          become_user: '{{ user }}'
          when: ansible_distribution=="Fedora"

        - name: Add {{ user }} to libvirt group
          user:
            name: '{{ user }}'
            groups: libvirt
            append: true
          when: ansible_distribution=="Debian"

        - name: Apply virt zsh config
          file:
            src: '{{ omz_path }}/virt_zsh'
            dest: '{{ local_config_path }}/omz/virt_zsh'
            state: link
            force: true
            owner: '{{ user }}'
            mode: 0700
          when: zsh_exist.stat.exists
          become_user: '{{ user }}'

      tags: virtualization

     # Kubernetes
    - name: Install kubernetes pkgs
      block:
        - name: Install minikube
          get_url:
            url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
            dest: '{{ local_bin_path }}/minikube'
            mode: 0700
          become_user: '{{ user }}'

        - name: Install kubectl
          block:
            - name: Get kubectl version
              set_fact:
                KUBECTL_VERSION: "{{ lookup('url', 'https://dl.k8s.io/release/stable.txt') }}"
            - name: Download kubectl
              get_url:
                url: https://dl.k8s.io/release/{{ KUBECTL_VERSION }}/bin/linux/amd64/kubectl
                dest: '{{ local_bin_path }}/kubectl'
                mode: 0700
          become_user: '{{ user }}'

        - name: Install kubens
          block:
            - name: Set pkg vars
              set_fact:
                github_username: ahmetb
                github_reponame: kubectx
                artifact_name: kubens
                arch_type: linux_x86_64
                extensoin: tar.gz
                pkg_name: kubens
            - name: Install {{ pkg_name }}
              include_tasks: '{{ ansible_path }}/_install_pkg_from_github.yml'

        - name: Install kubectx
          block:
            - name: Set pkg vars
              set_fact:
                github_username: ahmetb
                github_reponame: kubectx
                artifact_name: kubectx
                arch_type: linux_x86_64
                extensoin: tar.gz
                pkg_name: kubectx
            - name: Install {{ pkg_name }}
              include_tasks: '{{ ansible_path }}/_install_pkg_from_github.yml'

        - name: Apply kubernetes zsh config
          file:
            src: '{{ omz_path }}/k8s_zsh'
            dest: '{{ local_config_path }}/omz/k8s_zsh'
            state: link
            force: true
            owner: '{{ user }}'
            mode: 0700
          when: zsh_exist.stat.exists
          become_user: '{{ user }}'

      tags: kubernetes
