---
- name: Install additional packages
  hosts: localhost
  become: true

  tasks:
    - block:
        - name: Install pkgs
          dnf:
            name:
              - bat
              - bleachbit
              - cups
              - google-noto-emoji-color-fonts
              - google-noto-emoji-fonts
              - hplip
              - ibus-kkc
              - neofetch
              - net-tools
              - nmap
              - p7zip
              - perl-Image-ExifTool
              - s-tui
              - sane-backends-drivers-scanners
              - simple-scan
              - yt-dlp
            state: latest
            update_cache: true
            install_weak_deps: false

        - name: Autoremove pkgs
          dnf:
            autoremove: true

      when: ansible_distribution=="Fedora"
