---
- name: Apply local config
  hosts: localhost
  vars_files: [../vars.yml]
  tasks:
    - name: Apply local config
      include_tasks: '{{ ansible_path }}/_apply_local_config.yml'
    - name: Create local dirs
      include_tasks: '{{ ansible_path }}/_create_local_dirs.yml'
    - name: Debian config
      block:
        - name: Make autostart dir
          file:
            path: '{{ home_path }}/.config/autostart'
            state: directory
            owner: '{{ user }}'
            mode: 0755
        - name: Config RedShift
          block:
            - name: Apply RedShift config
              copy:
                src: '{{ config_path }}/redshift.conf'
                dest: '{{ home_path }}/.config/redshift.conf'
                mode: 0644
            - name: Autostart RedShift
              copy:
                src: '{{ config_path }}/autostart/redshift-gtk.desktop'
                dest: '{{ home_path }}/.config/autostart/redshift-gtk.desktop'
                mode: 0644
        - name: Autostart ibus
          copy:
            src: '{{ config_path }}/autostart/ibus-daemon.desktop'
            dest: '{{ home_path }}/.config/autostart/ibus-daemon.desktop'
            mode: 0644
      when: ansible_distribution=="Debian"
