---
- name: Install themes
  hosts: localhost
  become: true
  vars_files: [../vars.yml]
  vars:
    matcha_gtk_theme_path: '{{ local_opt_path }}/matcha_theme'
    qogir_icon_theme_path: '{{ local_opt_path }}/qogir_theme'
  tasks:
    - name: Install themes
      block:
        - name: Install Matcha GTK Theme
          block:
            - name: Clone Matcha theme repo
              git:
                repo: https://github.com/vinceliuice/Matcha-gtk-theme.git
                dest: '{{ matcha_gtk_theme_path }}'
                version: master
                clone: true
                update: true
              become_user: '{{ user }}'
            - name: Install Matcha theme
              shell:
                cmd: 'bash {{ matcha_gtk_theme_path }}/install.sh'
        - name: Install Qogir Icon Theme
          block:
            - name: Clone Qogir theme repo
              git:
                repo: https://github.com/vinceliuice/Qogir-icon-theme.git
                dest: '{{ qogir_icon_theme_path }}'
                version: master
                clone: true
                update: true
              become_user: '{{ user }}'
            - name: Install Qogir theme
              shell:
                cmd: 'bash {{ qogir_icon_theme_path }}/install.sh'
        - name: Enable themes
          shell:
            cmd: dconf load / <"{{ dconf_path }}/mate_theme.dconf"
          environment:
            DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{ uid }}/bus
          become_user: '{{ user }}'
      when: ansible_distribution=="Debian"
