---
- name: Remove other editors and install neovim
  block:
    - name: Fedora
      block:
        - name: Remove nano and vi(m) from Fedora
          dnf:
            name: [nano, vim*]
            state: absent
        - name: Install NeoVim to Fedora
          dnf:
            name: neovim
            state: latest
            update_cache: true
            install_weak_deps: false
      when: ansible_distribution=="Fedora"
    - name: Debian
      block:
        - name: Remove nano and vi(m) from Debian
          apt:
            name: [nano, vim*]
            state: absent
            autoremove: true
            purge: true
        - name: Install neovim to Debian
          apt:
            name: neovim
            state: latest
            update_cache: true
            install_recommends: false
      when: ansible_distribution=='Debian'
    - name: Config symlinks
      shell:
        cmd: |
          cd "{{ system_bin_path }}" || exit "$?"
          for link in edit vedit vi vim; do
              ln -s nvim "$link"
          done
          echo -e '#!/bin/sh\nexec nvim -e "$@"' >ex
          echo -e '#!/bin/sh\nexec nvim -R "$@"' >view
          echo -e '#!/bin/sh\nexec nvim -d "$@"' >vimdiff
          chmod 755 ex view vimdiff
        environment:

        creates: '{{ system_bin_path }}/vimdiff'
      when: ansible_distribution=='Fedora'
