---
- name: Install Docker
  block:
    - name: Get distro name
      set_fact:
        distro_name: '{{ (ansible_distribution | lower) }}'
    - name: Install docker to Fedora
      block:
        - name: Add repo to Fedora
          yum_repository:
            name: docker
            description: docker repository
            baseurl: https://download.docker.com/linux/{{ distro_name }}/$releasever/$basearch/stable
            enabled: true
            gpgcheck: true
            gpgkey: https://download.docker.com/linux/{{ distro_name }}/gpg
        - name: Install docker
          dnf:
            name: [docker-ce, docker-ce-cli, containerd.io]
            state: latest
            update_cache: true
            install_weak_deps: false
      when: ansible_distribution=="Fedora"
    - name: Install docker to Debian
      block:
        - name: Add gpg key and repo for Debian
          block:
            - name: Add key to Debian
              apt_key:
                url: https://download.docker.com/linux/debian/gpg
                state: present
            - name: Add repo to Debian
              apt_repository:
                repo: deb https://download.docker.com/linux/debian {{ ansible_lsb.codename }}
                  stable
                state: present
            - name: Install docker
              apt:
                name: [docker-ce, docker-ce-cli, containerd.io]
                state: latest
                update_cache: true
      when: ansible_distribution == "Debian"
    - name: Create Docker group
      group:
        name: docker
        state: present
    - name: Add user to docker group
      user:
        name: '{{ user }}'
        groups: docker
        append: true
    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true
