---
fedora_core_pkgs:
  - abattis-cantarell-fonts
  - bash-completion
  - gdm
  - git
  - gnome-shell
  - gnome-terminal
  - linux-firmware
  - mesa-dri-drivers
  - plymouth-theme-spinner

fedora_base_pkgs:
  - NetworkManager-openvpn-gnome
  - NetworkManager-wifi
  - baobab
  - ffmpegthumbnailer
  - file-roller
  - gnome-bluetooth
  - gnome-calculator
  - gnome-calendar
  - gnome-clocks
  - gnome-disk-utility
  - gnome-firmware
  - gnome-tweaks
  - gnome-weather
  - gvfs-mtp
  - htop
  - lm_sensors
  - nautilus
  - nautilus-gsconnect
  - nautilus-open-terminal
  - power-profiles-daemon
  - sqlite
  - sushi
  - unzip
  - xdg-desktop-portal-gnome
