---
fedora_core_pkgs:
  - abattis-cantarell-fonts
  - bash-completion
  - gdm
  - git
  - gnome-shell
  - gnome-terminal
  - linux-firmware
  - mesa-dri-drivers
  - plymouth-theme-spinner

fedora_base_pkgs:
  - NetworkManager-openvpn-gnome
  - NetworkManager-wifi
  - baobab
  - ffmpegthumbnailer
  - file-roller
  - gnome-bluetooth
  - gnome-calculator
  - gnome-calendar
  - gnome-clocks
  - gnome-disk-utility
  - gnome-firmware
  - gnome-tweaks
  - gnome-weather
  - gvfs-mtp
  - htop
  - lm_sensors
  - nautilus
  - nautilus-gsconnect
  - nautilus-open-terminal
  - power-profiles-daemon
  - sqlite
  - sushi
  - unzip
  - xdg-desktop-portal-gnome

debian_core_pkgs:
  - bash-completion
  - firmware-misc-nonfree
  - intel-microcode
  - xfonts-base
  - xserver-xorg-input-libinput
  - xserver-xorg-video-intel
  - zram-tools

debian_base_pkgs:
  - atril
  - blueman
  - caja-open-terminal
  - engrampa
  - eom
  - gnome-disk-utility
  - htop
  - lightdm
  - lightdm-gtk-greeter-settings
  - mate-applet-brisk-menu
  - mate-applets
  - mate-desktop-environment-core
  - mate-media
  - mate-notification-daemon
  - mate-screensaver
  - mate-sensors-applet
  - mate-tweak
  - mate-utils
  - network-manager-gnome
  - network-manager-openvpn-gnome
  - pluma
  - pulseaudio
  - rng-tools
  - tlp
  - unzip
