---
- name: Init Fedora configuration
  hosts: localhost
  become: true
  vars_files:
    - _vars_base.yml

  tasks:
    - block:
        - name: Configure dnf
          block:
            - name: Apply dnf config
              blockinfile:
                block: "{{ lookup('file', '{{ system_conf_path }}/dnf.conf') }}"
                path: /etc/dnf/dnf.conf
            - name: Disable OpenH264 repo
              shell:
                cmd: |
                  dnf config-manager --set-disabled fedora-cisco-openh264
                  dnf clean all
            - name: Install RPMFusion repo
              dnf:
                name:
                  - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
                  - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
                state: latest
                update_cache: true
                install_weak_deps: false
                disable_gpg_check: true

        - name: Install core pkgs
          dnf:
            name:
              - abattis-cantarell-fonts
              - bash-completion
              - gdm
              - git
              - gnome-shell
              - gnome-terminal
              - linux-firmware
              - mesa-dri-drivers
              - plymouth-theme-spinner
            state: latest
            update_cache: true
            install_weak_deps: false

        - name: Base configuration
          block:
            - name: Enable gdm
              systemd:
                name: gdm
                enabled: true
            - name: Set graphical.target
              command:
                cmd: systemctl set-default graphical.target
            - name: Set plymouth theme
              command:
                cmd: plymouth-set-default-theme bgrt --rebuild-initrd
            - name: Hide grub on startup
              shell:
                cmd: |
                  grub2-editenv - set menu_auto_hide=1
                  grub2-mkconfig -o /boot/grub2/grub.cfg

        - name: Install base pkgs
          dnf:
            name:
              - NetworkManager-openvpn-gnome
              - NetworkManager-wifi
              - baobab
              - ffmpegthumbnailer
              - file-roller
              - gnome-bluetooth
              - gnome-calculator
              - gnome-calendar
              - gnome-clocks
              - gnome-disk-utility
              - gnome-firmware
              - gnome-tweaks
              - gnome-weather
              - gvfs-mtp
              - htop
              - lm_sensors
              - nautilus
              - nautilus-gsconnect
              - nautilus-open-terminal
              - power-profiles-daemon
              - sqlite
              - sushi
              - unzip
              - xdg-desktop-portal-gnome
            state: latest
            update_cache: true
            install_weak_deps: false

        - name: Make nested BTRFS volumes
          script:
            cmd: '{{ script_path }}/_make_btrfs_subvols.sh {{ item }}'
          environment:
            BACKUP_PATH: '{{ backup_path }}'
          become_user: '{{ user }}'
          with_items: ['{{ home_path }}/.var var']

      when: ansible_distribution=="Fedora"
