---
- name: Install NeoVim
  hosts: localhost
  become: true

  vars:
    system_bin_path: /usr/bin

  tasks:
    - name: Remove other editors
      block:
        - name: Remove nano and vi(m) from Fedora
          dnf:
            name:
              - nano
              - vim*
            state: absent
          when: ansible_distribution=="Fedora"

    - name: Install NeoVim
      block:
        - name: Install NeoVim to Fedora
          dnf:
            name: neovim
            state: latest
            update_cache: true
            install_weak_deps: false
          when: ansible_distribution=="Fedora"

    - name: Config symlinks
      shell:
        cmd: |
          cd "$BIN_PATH" || exit "$?"

          for link in edit vedit vi vim; do
              ln -s nvim "$link"
          done

          echo -e '#!/bin/sh\nexec nvim -e "$@"' >ex
          echo -e '#!/bin/sh\nexec nvim -R "$@"' >view
          echo -e '#!/bin/sh\nexec nvim -d "$@"' >vimdiff
          chmod 755 ex view vimdiff
        creates: '{{ system_bin_path }}/vimdiff'
      environment:
        BIN_PATH: '{{ system_bin_path }}'
