---
- name: Install themes
  hosts: localhost
  become: true
  vars_files: [./vars.yml]

  tasks:
    # Fedora (Gnome)
    - name: Install Fedora themes
      block:
        - name: Add adw-gtk3 copr repo
          community.general.copr:
            name: nickavem/adw-gtk3
            state: enabled

        - name: Install adw-gtk3 gtk theme and Papirus icon theme
          dnf:
            name: [adw-gtk3, papirus-icon-theme]
            state: latest
            update_cache: true
            install_weak_deps: false

        # - name: Install flatpak themes
        #   block:
        #     - name: Check flathub repo
        #       shell:
        #         cmd: |
        #           flatpak remote-list | grep "flathub" >/dev/null
        #           echo "$?"
        #       register: flatpak_return
        #     - name: Install themes
        #       block:
        #         - name: Install adw-gtk3 theme
        #           flatpak:
        #             name: org.gtk.Gtk3theme.adw-gtk3-dark
        #             state: present
        #       when: flatpak_return.stdout=="0"

        - name: Enable themes
          shell:
            cmd: dconf load / <"{{ dconf_path }}/gnome_theme.dconf"
          environment:
            DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{ uid }}/bus
          become_user: '{{ user }}'

      when: ansible_distribution=="Fedora"

    # Debian (Mate)
    - name: Install themes
      block:
        - name: Set theme path
          set_fact:
            matcha_gtk_theme_path: '{{ local_opt_path }}/matcha_theme'
            qogir_icon_theme_path: '{{ local_opt_path }}/qogir_theme'

        - name: Install Matcha GTK Theme
          block:
            - name: Clone Matcha theme repo
              git:
                repo: https://github.com/vinceliuice/Matcha-gtk-theme.git
                dest: '{{ matcha_gtk_theme_path }}'
                version: master
                clone: true
                update: true
              become_user: '{{ user }}'
            - name: Install Matcha theme
              shell:
                cmd: bash {{ matcha_gtk_theme_path }}/install.sh

        - name: Install Qogir Icon Theme
          block:
            - name: Clone Qogir theme repo
              git:
                repo: https://github.com/vinceliuice/Qogir-icon-theme.git
                dest: '{{ qogir_icon_theme_path }}'
                version: master
                clone: true
                update: true
              become_user: '{{ user }}'
            - name: Install Qogir theme
              shell:
                cmd: bash {{ qogir_icon_theme_path }}/install.sh

        # - name: Install flatpak themes
        #   block:
        #     - name: Check flathub repo
        #       shell:
        #         cmd: |
        #           flatpak remote-list | grep "flathub" >/dev/null
        #           echo "$?"
        #       register: flatpak_return
        #     - name: Install themes
        #       block:
        #         - name: Install Matcha-dark-aliz GTK theme
        #           flatpak:
        #             name: org.gtk.Gtk3theme.Matcha-dark-aliz
        #             state: present
        #       when: flatpak_return.stdout=="0"

        - name: Enable themes
          shell:
            cmd: dconf load / <"{{ dconf_path }}/mate_theme.dconf"
          environment:
            DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{ uid }}/bus
          become_user: '{{ user }}'

        - name: Set LightDM themes
          block:
            - name: Set LightDM GTK theme
              lineinfile:
                dest: /etc/lightdm/lightdm-gtk-greeter.conf
                regexp: ^theme-name =
                line: theme-name = Matcha-dark-aliz
                state: present
            - name: Set LightDM icon theme
              lineinfile:
                dest: /etc/lightdm/lightdm-gtk-greeter.conf
                regexp: ^icon-theme-name =
                line: icon-theme-name = Qogir-ubuntu-dark
                state: present

      when: ansible_distribution=="Debian"
