---
- name: Install NVIDIA firmware and drivers
  hosts: localhost

  vars_files:
    - _vars_base.yml
    - _vars_firmware_pkgs.yml

  pre_tasks:
    - name: Preparatory steps
      block:
        - name: Add RPMFusion repo
          dnf:
            name:
              - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
              - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
            state: latest
            update_cache: true
            install_weak_deps: false
            disable_gpg_check: true

        - name: Hide grub during boot
          lineinfile:
            dest: /etc/default/grub
            regexp: ^GRUB_TIMEOUT=
            line: GRUB_TIMEOUT=0
            state: present

      become: true
      tags: prepare

  tasks:
    - name: Install NVIDIA to Fedora
      block:
        - name: Install and configure signing modules
          block:
            - name: Install necessary packages for signing modules
              dnf:
                name:
                  - kmodtool
                  - akmods
                  - mokutil
                  - openssl
                state: latest
                update_cache: true
                install_weak_deps: false

            - name: Generate a key for signing modules
              command: kmodgenca -a
              args:
                creates: /etc/pki/akmods/certs/public_key.der

            - name: Import key for MOK
              command: mokutil --import /etc/pki/akmods/certs/public_key.der

          tags: nvidia_secureboot
          become: true

        - name: Install NVIDIA firmware and drivers to Fedora
          block:
            - name: Install NVIDIA drivers
              dnf:
                name:
                  - akmod-nvidia
                  - xorg-x11-drv-nvidia
                  - xorg-x11-drv-nvidia-libs
                  - xorg-x11-drv-nvidia-power
                  - nvidia-settings
                state: present

            - name: Install CUDA
              dnf:
                name: xorg-x11-drv-nvidia-cuda
                state: present

            - name: Wait for NVIDIA modules to build
              shell: |
                until modinfo -F version nvidia; do
                  sleep 5
                done

            - name: Recompile and install kernel modules
              command: akmods --force

            - name: Recreates the initramfs image
              command: dracut --force

          tags: nvidia_firmware
          become: true

      when: ansible_distribution=="Fedora"
