---
- name: Backup and apply dotfiles
  hosts: localhost
  become: true

  vars:
    user: '{{ ansible_env.SUDO_USER }}'

  tasks:
    - name: Run load_dotfiles.sh
      shell:
        cmd: bash ./../scripts/_load_dotfiles.sh
      become_user: '{{ user }}'
  # TODO: make this script as module
