---
- name: Upgrade Linux system
  hosts: localhost

  tasks:
    # Built-in package manager
    - name: Upgrade distro
      block:
        - name: Update and upgrade packages
          package:
            name: '*'
            state: latest

        - name: Autoremove unneeded packages (Debian based)
          apt:
            autoremove: true
          when: ansible_os_family == "Debian"

        - name: Autoremove unneeded packages (Red Hat based)
          dnf:
            autoremove: true
          when: ansible_os_family == "RedHat"

      become: true

    # Flatpak
    - name: Update Flatpak Packages
      block:
        - name: Check if Flatpak is installed
          shell: which flatpak
          register: flatpak
          ignore_errors: true

        - name: Update Flatpak PKGs
          shell: flatpak update -y
          when: flatpak.rc == 0

        - name: Remove unused Flatpak runtimes
          shell: flatpak uninstall --unused --delete-data -y
          when: flatpak.rc == 0

