---
- name: Install dev pkgs
  hosts: localhost
  become: true
  vars_files: [../vars.yml]
  tasks:
    - name: Install pkgs from distro repo
      block:
        - name: Install pkgs to Fedora
          dnf:
            name:
              - distrobox
              - gnome-boxes
              - jetbrains-mono-fonts
              - vagrant
              - vagrant-libvirt
              - vagrant-sshfs
            state: latest
            update_cache: true
            install_weak_deps: false
        - name: Config VM images dirs
          shell:
            cmd: |
              GNOME_BOXES_DIR_NAME="gnome-boxes"
              GNOME_BOXES_LOCAL_PATH="$local_share_path/$GNOME_BOXES_DIR_NAME"
              GNOME_BOXES_LOCAL_IMAGES_PATH="$GNOME_BOXES_LOCAL_PATH/images"
              LIBVIRT_DIR_NAME="libvirt"
              LIBVIRT_LOCAL_PATH="$local_share_path/$LIBVIRT_DIR_NAME"
              LIBVIRT_LOCAL_IMAGES_PATH="$LIBVIRT_LOCAL_PATH/images"
              backupDirs() {
                  local dirName="$1"
                  local dirToBackup="$2"
                  if [[ -d $dirToBackup ]]; then
                      local currentTimestamp=""
                      currentTimestamp="$(date +'%d_%m_%Y_%H_%M_%S')"
                      mv "$dirToBackup" "$BACKUP_PATH/${dirName}_$currentTimestamp"
                  fi
              }
              configDir() {
                local dirName="$1"
                local vmPath="$2"
                local vmImagesPath="$3"
                backupDirs "$dirName" "$vmPath" 
                mkdir -p "$vmPath"
                btrfs subvolume create "$vmImagesPath"
                chattr +C "$vmImagesPath"
              }
              configDir "$GNOME_BOXES_DIR_NAME" "$GNOME_BOXES_LOCAL_PATH" "$GNOME_BOXES_LOCAL_IMAGES_PATH"
              configDir "$LIBVIRT_DIR_NAME" "$LIBVIRT_LOCAL_PATH" "$LIBVIRT_LOCAL_IMAGES_PATH"
              echo "Done"
          environment:
            BACKUP_PATH: '{{ backup_path }}'
            local_share_path: '{{ local_share_path }}'
          become_user: '{{ user }}'
        - name: Install VSCodium
          include_tasks: ../_install_vscodium.yml
      when: ansible_distribution=="Fedora"
