---
- name: Install additional packages
  hosts: localhost
  become: true
  vars_files: [../vars.yml]
  tasks:
    - block:
        - name: Install pkgs
          dnf:
            name:
              - bat
              - bleachbit
              - cups
              - google-noto-emoji-color-fonts
              - google-noto-emoji-fonts
              - webp-pixbuf-loader
              - hplip
              - ibus-kkc
              - jetbrains-mono-fonts
              - liberation-fonts
              - neofetch
              - net-tools
              - nmap
              - p7zip
              - perl-Image-ExifTool
              - s-tui
              - sane-backends-drivers-scanners
              - simple-scan
              - tree
              - yt-dlp
              - zip
            state: latest
            update_cache: true
            install_weak_deps: false
        - name: Autoremove pkgs
          dnf:
            autoremove: true
      when: ansible_distribution=="Fedora"
    - name: Install Oh My ZSH
      include_tasks: '{{ ansible_path }}/_install_omz.yml'
    - name: Install NeoVim
      include_tasks: '{{ ansible_path }}/_install_nvim.yml'
