---
- name: Install themes
  hosts: localhost
  become: true
  vars_files: [../vars.yml]
  tasks:
    - name: Install themes
      block:
        - name: Add adw-gtk3 copr repo
          community.general.copr:
            name: nickavem/adw-gtk3
            state: enabled
        - name: Install adw-gtk3 gtk theme and Papirus icon theme
          dnf:
            name: [adw-gtk3, papirus-icon-theme]
            state: latest
            update_cache: true
            install_weak_deps: false
        # - name: Install flatpak themes
        #   block:
        #     - name: Check flathub repo
        #       shell:
        #         cmd: |
        #           flatpak remote-list | grep "flathub" >/dev/null
        #           echo "$?"
        #       register: flatpak_return
        #     - name: Install themes
        #       block:
        #         - name: Install adw-gtk3 theme
        #           flatpak:
        #             name: org.gtk.Gtk3theme.adw-gtk3-dark
        #             state: present
        #       when: flatpak_return.stdout=="0"
        - name: Enable themes
          shell:
            cmd: dconf load / <"{{ dconf_path }}/gnome_theme.dconf"
          environment:
            DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{ uid }}/bus
          become_user: '{{ user }}'
      when: ansible_distribution=="Fedora"
