---
- name: Init configuration
  hosts: localhost
  become: true

  vars:
    user: '{{ ansible_env.SUDO_USER }}'
# Local path
    local_path: '{{ ansible_user_dir }}/.local'
    bin_path: '{{ local_path }}/bin'
    games_path: '{{ local_path }}/games'
    lib_path: '{{ local_path }}/lib'
    opt_path: '{{ local_path }}/opt'

  tasks:
    - name: Crete local dirs
      file:
        path: '{{ item }}'
        state: directory
        mode: 0700
        owner: '{{ ansible_user_id }}'
      become_user: '{{ user }}'
      with_items:
        - '{{ bin_path }}'
        - '{{ games_path }}'
        - '{{ lib_path }}'
        - '{{ opt_path }}'

    - name: Config network
      block:
        - name: Get wifi mac addres
          shell:
            cmd: |
              INTERFACE_NAME=$(ip link show | grep "wl" | awk '{print $2}' | tr -d ':')
              ip link show "$INTERFACE_NAME" 2>/dev/null | awk '/permaddr/ {print $6}'
          register: getMacAddr
        - set_fact:
            MAC_ADDR: '{{ getMacAddr.stdout }}'

        - name: Apply systemd-network config
          template:
            src: ./../system_conf/systemd_networkd/{{ item }}.j2
            dest: /etc/systemd/network/{{ item }}.network
            mode: 0644
          with_items:
            - 00-wifi
            - 10-net

        - name: Make NetworkManager config dir
          file:
            path: /etc/NetworkManager/conf.d
            state: directory
            recurse: true
            mode: 0755

        - name: Apply NetworkManager config
          copy:
            src: ./../system_conf/nm.conf
            dest: /etc/NetworkManager/conf.d
            mode: 0644

      notify: Restart NetworkManager

  handlers:
    - name: Restart NetworkManager
      service:
        name: NetworkManager
        state: restarted