---
- name: Install gaming packages
  hosts: localhost
  become: true

  vars:
    user: '{{ ansible_env.SUDO_USER }}'

  tasks:
    - block:
        - name: Install Bottles
          flatpak:
            name: com.usebottles.bottles
            state: latest

        - name: Configure permissions for Bottles
          shell:
            cmd: >
              flatpak override --user \
              --filesystem=xdg-data/applications \
              com.usebottles.bottles

      become_user: '{{ user }}'
